name: 'demo'
version: '1.0.0'
config-version: 2

profile: 'demo'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" 
clean-targets:
    - "target"
    - "dbt_modules"

models:
    sde_dbt_tutorial:
        marts:
            core:
                materialized: table